site_name: 代理模拟器
# 参考链接：https://blog.csdn.net/m0_63203517/article/details/129765689

#repo_url: https://github.com/carla-simulator/carla
#docs_dir: Docs
#edit_uri: 'edit/master/Docs/'


# 设置编译页面的链接的前缀
repo_url: https://github.com/OpenHUTB/carla_doc

# 页面右上角添加直接编辑页面的按钮
edit_uri: edit/master/docs/

theme:
  name: readthedocs
  sticky_navigation: True
  navigation_depth: 3
  features:
    - search.suggest # 在目录栏中的搜索框中输入一些字母时推荐补全整个单词
extra_css: [extra.css]



# mathjax用于单独公式展示
extra_javascript:
  - extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

plugins:
#  - mkdocs-video
  - search:
      lang: ja
      separator: '[\s\-\.]+'
      min_search_length: 2

extra:
  generator: false

nav:
- 简介:
    - 介绍: start_introduction.md
    - 快速启动: start_quickstart.md
    - 第一步: tuto_first_steps.md
    - 教程: tutorials.md
    - 示例: tuto_E_gallery.md
    - 智能驾驶: ecosys_iss.md
- 主题:
    - 基础: foundations.md
    - 第一、 世界和客户端: core_world.md
    - 第二、 参与者和蓝图: core_actors.md
    - 第三、地图和导航: core_map.md
    - 第四、 传感器和数据: core_sensors.md
    - 开发: development_tutorials.md
    - 自定义资产: custom_assets_tutorials.md
    - 内容创作-地图: tuto_content_authoring_maps.md
    - 内容创作-车辆: tuto_content_authoring_vehicles.md
- 主题:
    - 交通模拟概述: ts_traffic_simulation_overview.md
    - 交通管理器: adv_traffic_manager.md
    - 和 SUMO 协同模拟: adv_sumo.md
    - Scenic: tuto_G_scenic.md
- 主题:
    - 行人导航: tuto_G_pedestrian_navigation.md
    - 控制行人骨架: tuto_G_control_walker_skeletons.md
    - 行人视觉: tuto_G_pedestrian_visual.md
    - 生成行人导航: tuto_M_generate_pedestrian_navigation.md
    - 行人建模: tuto_content_authoring_pedestrians.md
    - 行人物理场模拟: pedestrian/tuto_content_chrono_opensim.md
- 主题:
    - OpenDRIVE 独立模式: adv_opendrive.md
    - 记录器: adv_recorder.md
    - 渲染选项: adv_rendering_options.md
    - 责任敏感安全: adv_rss.md
    - 同步和时间步长: adv_synchrony_timestep.md
    - Carla 代理: adv_agents.md
    - Carla 配置: carla_settings.md
    - Carla 模拟器键盘输入: simulator_keyboard_input.md
    - 无显示屏运行 Carla 并选择 GPU: carla_headless.md
    - 链接 Epic 的汽车材质: epic_automotive_materials.md
- 自定义地图:
    - Carla 中自定义地图的概述: tuto_M_custom_map_overview.md
    - 在 RoadRunner 中创建地图: tuto_M_generate_map.md
    - 在 Carla 包导入地图: tuto_M_add_map_package.md
    - 在 Carla 源构建中导入地图: tuto_M_add_map_source.md
    - 导入地图的替代方法: tuto_M_add_map_alternative.md
    - 手动准备地图包: tuto_M_manual_map_package.md
    - 自定义地图：分层地图: tuto_M_custom_layers.md
    - 自定义地图：交通灯和标志: tuto_M_custom_add_tl.md
    - 自定义地图：道路画家: tuto_M_custom_road_painter.md
    - 自定义地图：天气和景观: tuto_M_custom_weather_landscape.md
    - 使用 OpenStreetMap 生成地图: tuto_G_openstreetmap.md
    - 自定义地图：程序建筑: tuto_M_custom_buildings.md
    - 程序化建筑工具: adv_procedural_building_tool.md
    - 数字孪生工具: adv_digital_twin.md
    - 大地图概述: large_map_overview.md
    - 在 RoadRunner 中创建大地图: large_map_roadrunner.md
    - 导入/打包大地图: large_map_import.md
- 自定义开发:
    - 添加摩擦触发器: tuto_G_add_friction_triggers.md
    - 控制车辆物理模型: tuto_G_control_vehicle_physics.md
    - 检索模拟数据: tuto_G_retrieve_data.md
    - 在 Docker 中构建虚幻引擎和 Carla: build_docker_unreal.md
    - 添加新车辆: tuto_A_add_vehicle.md
    - 添加新道具: tuto_A_add_props.md
    - 创建独立包: tuto_A_create_standalone.md
    - 材料定制: tuto_A_material_customization.md
    - 如何升级内容: tuto_D_contribute_assets.md
    - 创建一个传感器: tuto_D_create_sensor.md
    - 创建语义标签: tuto_D_create_semantic_tags.md
    - 自定义车辆悬架: tuto_D_customize_vehicle_suspension.md
    - 生成详细碰撞: tuto_D_generate_colliders.md
    - 虚幻引擎常见问题: ue/ue_faq.md
    - 发布版本: tuto_D_make_release.md
- 基准测试:
    - 自动驾驶排行榜: leaderboard.md
    - 驾驶基准: benchmark_start.md
    - 基准性能: adv_benchmarking.md
    - 驾驶基准结构: benchmark_structure.md
    - 测试代理: benchmark_creating.md
    - 计算的基准性能指标: benchmark_metrics.md
- 生态系统:
    - 交通场景: scenario_runner.md
    - Web 可视化器: plugins_carlaviz.md
    - ROS: ros_documentation.md
    - CarSim 集成: tuto_G_carsim_integration.md
    - RLlib 集成: tuto_G_rllib_integration.md
    - Chrono 集成: tuto_G_chrono.md
    - OpenRadios 有限元模拟: OpenRadioss/use_OpenRadioss_windows.md
    - PTV-Vissim 联合模拟: adv_ptv.md
    - Ansys 实时雷达模型: ecosys_ansys.md
    - Matlab 接口: https://github.com/darkscyla/MATLAB-Carla-Interface
    - 罗技 G29 方向盘: tuto_G_G29_windows.md
    - OpenSCENARIO 播放器: tuto_G_esmini.md
    - 有限元变形材料虚幻插件: ecosys_femfx.md
    - 地理空间生态系统: adv_cesium.md
    - 应用Carla的仓库列表: used_by.md
- 源代码编译:
    - 编译 Carla: build_carla.md
    - Linux 上编译: build_linux.md
    - Windows 上编译: build_windows.md
    - Carla 更新: build_update.md
    - 构建系统: build_system.md
    - Docker 中的 Carla: build_docker.md
    - 常见问题: build_faq.md
    - 调试程序: tuto_D_windows_debug.md
- 其他:
    - RoadRunner: https://ww2.mathworks.cn/help/roadrunner/index.html)
    - RoadRunner Scenario: https://ww2.mathworks.cn/help/roadrunner-scenario/index.html
    - Carla 相关的第三方链接: third.md
    - 虚幻引擎: tuto_G_unreal.md
    - Blender 手册: https://docs.blender.org/manual/zh-hans/latest/
    - 文件说明: file_specification.md
    - 待做列表: todo.md
- 参考:
    - Python API 参考: python_api.md
    - C++ 参考: ref_cpp.md
    - 资源目录: catalogue.md
    - 传感器: ref_sensors.md
    - 蓝图库: bp_library.md
    - 记录器二进制文件格式: ref_recorder_binary_file_format.md
    - 测量和数据包: measurements.md
    - 扩展文档: ext_docs.md

# - mdx_math 用于行内公式显示
markdown_extensions:
  - admonition
  - mdx_math
