site_name: 交通仿真器文档

#repo_url: https://github.com/carla-simulator/carla
#docs_dir: Docs
#edit_uri: 'edit/master/Docs/'
theme:
  name: readthedocs
  sticky_navigation: True
  navigation_depth: 3
extra_css: [extra.css]
extra_javascript: [extra.js]

plugins:
  - search:
      lang: ja
      separator: '[\s\-\.]+'
      min_search_length: 2

extra:
  generator: false

nav:
- 主页: 'index.md'
- 入门:
  - '介绍': 'start_introduction.md'
  - '快速启动包安装': 'start_quickstart.md'
  - '第一步' : 'tuto_first_steps.md'
  - '教程': 'tutorials.md'
- 构建 Carla:
  - '构建 Carla' : 'build_carla.md'
  - 'Linux 构建': 'build_linux.md'
  - 'Windows 构建': 'build_windows.md'
  - '更新 Carla': 'build_update.md'
  - '构建系统': 'build_system.md'
  - 'Docker 中的 Carla': 'build_docker.md'
  - '常问的问题': 'build_faq.md'
- 下一步:
  - '内容创作 - 地图': 'tuto_content_authoring_maps.md'  
  - '内容创作 - 车辆': 'tuto_content_authoring_vehicles.md'
- Carla 主题:
  - '基础': 'foundations.md'
  - '核心概念': 'core_concepts.md'
  - '世界和客户端': 'core_world.md'
  - '参与者和蓝图': 'core_actors.md'
  - '交通' : 'ts_traffic_simulation_overview.md'
  - '地图和导航 ': 'core_map.md'
  - '传感器和数据': 'core_sensors.md'
  - '开发': 'development_tutorials.md'
  - '自定义资产': 'custom_assets_tutorials.md'
- 交通仿真:
  - '交通管理器': 'adv_traffic_manager.md'
  - '和 SUMO 联合仿真': 'adv_sumo.md'
  - 'Scenic': 'tuto_G_scenic.md'
- 高级概念:
  - '记录器': 'adv_recorder.md'
  - '渲染选项': 'adv_rendering_options.md'
  - '同步和时间步长': 'adv_synchrony_timestep.md'
  - '基准性能': 'adv_benchmarking.md'
  - 'Carla 智能体': 'adv_agents.md'
- 资源:
  - 'Python API 参考': 'python_api.md'
  - 'C++ 参考' : 'ref_cpp.md'
  - '蓝图库': 'bp_library.md'
  - 'Carla 目录': 'catalogue.md'  
  - '记录器二进制文件格式': 'ref_recorder_binary_file_format.md'
  - "传感器参考": 'ref_sensors.md'
  - '扩展文档': 'ext_docs.md'
- 自定义地图:
  - 'Carla 中自定义地图的概述': 'tuto_M_custom_map_overview.md'
  - '在 RoadRunner 中创建地图': 'tuto_M_generate_map.md'
  - '在 Carla 包导入地图': 'tuto_M_add_map_package.md'
  - '在 Carla 源构建中导入地图': 'tuto_M_add_map_source.md'
  - '导入地图的替代方法': 'tuto_M_add_map_alternative.md'
  - '手动准备地图包': 'tuto_M_manual_map_package.md'
  - '自定义地图：分层地图': 'tuto_M_custom_layers.md'
  - '自定义地图：红绿灯和标志': 'tuto_M_custom_add_tl.md'
  - '自定义地图：道路画家': 'tuto_M_custom_road_painter.md'
  - '自定义地图：程序建筑': 'tuto_M_custom_buildings.md'
  - '自定义地图：天气和景观': 'tuto_M_custom_weather_landscape.md'
  - '生成行人导航': 'tuto_M_generate_pedestrian_navigation.md'
- 大型地图:
  - '大型地图概述': 'large_map_overview.md'
  - '在RoadRunner中创建大地图': 'large_map_roadrunner.md'
  - '导入/打包大地图': 'large_map_import.md'
- 教程（通用）:
  - '添加摩擦触发器': "tuto_G_add_friction_triggers.md"
  - '控制车辆物理模型': "tuto_G_control_vehicle_physics.md"
  - '控制行人骨骼': "tuto_G_control_walker_skeletons.md"
  - '使用 OpenStreetMap 生成地图': 'tuto_G_openstreetmap.md'
  - '检索仿真数据': "tuto_G_retrieve_data.md"
  - '在 Docker 中构建虚幻引擎和 Carla': 'build_docker_unreal.md'
- 教程（资产）:
  - '添加新车辆': 'tuto_A_add_vehicle.md'
  - '添加新道具': 'tuto_A_add_props.md'
  - '创建独立包': 'tuto_A_create_standalone.md'
  - "材质定制": 'tuto_A_material_customization.md'
- 教程（开发人员）:
  - '如何升级内容': 'tuto_D_contribute_assets.md'
  - '创建一个传感器': 'tuto_D_create_sensor.md'
  - '创建语义标签': 'tuto_D_create_semantic_tags.md'
  - '自定义车辆悬架': 'tuto_D_customize_vehicle_suspension.md'
  - '生成详细碰撞': 'tuto_D_generate_colliders.md'
  - '发布版本': 'tuto_D_make_release.md'
- Carla 生态系统:
  - 'Ansys 实时雷达模型': 'ecosys_ansys.md'
  - 'RLlib 集成': "tuto_G_rllib_integration.md"
  - 'CarSim 集成': "tuto_G_carsim_integration.md"
  - 'Chrono 集成': 'tuto_G_chrono.md'
  - 'OpenDRIVE 独立模式': 'adv_opendrive.md'
  - 'PTV-Vissim 联合仿真': 'adv_ptv.md'
  - 'ROS': 'ros_documentation.md'
  - '责任敏感安全': 'adv_rss.md'
  - '虚幻引擎教程': https://github.com/OpenHUTB/engine_doc
  - 'Web 可视化器': 'plugins_carlaviz.md'
  - '罗技 G29 方向盘': 'tuto_G_G29_windows.md'
- 贡献:
  - '贡献指南': 'cont_contribution_guidelines.md'
  - '行为准则': 'cont_code_of_conduct.md'
  - '编码标准': 'cont_coding_standard.md'
  - '文档标准': 'cont_doc_standard.md'

markdown_extensions:
  - admonition

